apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-infotrygd-poller
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  kafka:
    pool: nav-dev
  envFrom:
    - secret: srvhm-infotrygdpoller-secret
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  liveness:
    path: /isalive
  readiness:
    path: /isready
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: a01dbfl033.adeo.no